[package]
name = "gallium_ecs_derive"
version = "0.1.1"
edition = "2018"
description = "Proc-macros for gallium_ecs"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "0.11.11"

[lib]
proc-macro = true